---
abstract: 'Simple testing of Catalyst controllers'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-PseudoCatalyst
provides:
  Catalyst::PseudoCatalyst:
    file: lib/Catalyst/PseudoCatalyst.pm
    version: 0.04
  Catalyst::PseudoCatalyst::Action:
    file: lib/Catalyst/PseudoCatalyst/Action.pm
    version: 0
  Catalyst::PseudoCatalyst::Request:
    file: lib/Catalyst/PseudoCatalyst/Request.pm
    version: 0
  Catalyst::PseudoCatalyst::Request::Upload:
    file: lib/Catalyst/PseudoCatalyst/Request/Upload.pm
    version: 0
  Catalyst::PseudoCatalyst::Response:
    file: lib/Catalyst/PseudoCatalyst/Response.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
